FROM golang:1.20.5 AS build
COPY . /tmp/build
WORKDIR /tmp/build
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o=/main

# copy artifacts to a clean image
FROM public.ecr.aws/lambda/provided:al2
COPY --from=build /main /main
ENTRYPOINT [ "/main" ]